# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e",
  "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/actuators",
  "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler",
  "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra",
  "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators",
  "github.com/openshift/api/config/v1",
  "github.com/onsi/ginkgo",
  "github.com/onsi/gomega",
]

# To override the branch="master" constraint from cluster-api-actuator-pkg
# for github.com/openshift/cluster-autoscaler-operator
[[override]]
  name = "github.com/openshift/cluster-autoscaler-operator"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/kube-aggregator"
  branch = "release-1.12"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  # version = "v0.1.8" # does not work, still pulls v.1.10 instead
  revision = "c63ebda0bf4be5f0a8abd4003e4ea546032545ba"

[[override]]
  name = "github.com/openshift/api"
  branch = "master"

[[override]]
  name = "github.com/openshift/client-go"
  branch = "master"

[[override]]
  name = "github.com/openshift/cluster-version-operator"
  branch = "master"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "github.com/openshift/cluster-api-actuator-pkg"
    go-tests = false

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"
