apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusterautoscalers.autoscaling.openshift.io
spec:
  group: autoscaling.openshift.io
  names:
    kind: ClusterAutoscaler
    listKind: ClusterAutoscalerList
    plural: clusterautoscalers
    singular: clusterautoscaler
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            maxPodGracePeriod:
              format: int32
              type: integer
            podPriorityThreshold:
              format: int32
              type: integer
            resourceLimits:
              properties:
                cores:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      minimum: 0
                      type: integer
                  required:
                  - min
                  - max
                  type: object
                gpus:
                  items:
                    properties:
                      type:
                        minLength: 1
                        type: string
                    required:
                    - type
                    type: object
                  type: array
                maxNodesTotal:
                  format: int32
                  minimum: 0
                  type: integer
                memory:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      minimum: 0
                      type: integer
                  required:
                  - min
                  - max
                  type: object
              type: object
            scaleDown:
              properties:
                delayAfterAdd:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                delayAfterDelete:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                delayAfterFailure:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                enabled:
                  type: boolean
                unneededTime:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
              required:
              - enabled
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
