apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: machineautoscalers.autoscaling.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.scaleTargetRef.kind
    description: Kind of object scaled
    name: Ref Kind
    type: string
  - JSONPath: .spec.scaleTargetRef.name
    description: Name of object scaled
    name: Ref Name
    type: string
  - JSONPath: .spec.minReplicas
    description: Min number of replicas
    name: Min
    type: integer
  - JSONPath: .spec.maxReplicas
    description: Max number of replicas
    name: Max
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: autoscaling.openshift.io
  names:
    kind: MachineAutoscaler
    listKind: MachineAutoscalerList
    plural: machineautoscalers
    singular: machineautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            maxReplicas:
              format: int32
              minimum: 1
              type: integer
            minReplicas:
              format: int32
              minimum: 0
              type: integer
            scaleTargetRef:
              properties:
                apiVersion:
                  type: string
                kind:
                  minLength: 1
                  type: string
                name:
                  minLength: 1
                  type: string
              required:
              - kind
              - name
              type: object
          required:
          - minReplicas
          - maxReplicas
          - scaleTargetRef
          type: object
        status:
          properties:
            lastTargetRef:
              properties:
                apiVersion:
                  type: string
                kind:
                  minLength: 1
                  type: string
                name:
                  minLength: 1
                  type: string
              required:
              - kind
              - name
              type: object
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
