---
apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler-operator
  namespace: openshift-machine-api
  labels:
    k8s-app: cluster-autoscaler-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: cluster-autoscaler-operator-cert
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    k8s-app: cluster-autoscaler-operator
  sessionAffinity: None
