---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-operator-ca
  namespace: openshift-machine-api
  labels:
    k8s-app: cluster-autoscaler-operator
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
data:
