apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cluster-autoscaler
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
