apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cluster-autoscaler-operator-rules
  namespace: openshift-machine-api
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  groups:
    - name: Cluster-autoscaler-operator-down
      rules:
        - alert: ClusterAutoscalerOperatorDown
          annotations:
            message: cluster-autoscaler-operator has disappeared from Prometheus target discovery.
          expr: |
            absent(up{job="cluster-autoscaler-operator"} == 1)
          for: 5m
          labels:
            severity: critical
